forge_support: false
connection_throttle_limit: 3
timeout: 30000
online_mode: false
log_commands: false
listeners:
- query_port: 25577
  motd: '&aBungeeCord sunucusu'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - skyblock
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
connection_throttle: -1
groups:
  md_5:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
network_compression_threshold: -1
disabled_commands:
- disabledcommandhere
stats: 9a8ffb02-a428-48a9-be60-972eec0d9458
permissions:
  default: null
  admin: null
servers:
  lobi:
    motd: '&6Lobi sunucusu (Giriş sunucusu)'
    address: localhost:25566
    restricted: false
  skyblock:
    motd: '&6Skyblock sunucusu'
    address: localhost:25567
    restricted: false
  factions:
    motd: '&6Factions sunucusu'
    address: localhost:25568
    restricted: false
  survival:
    motd: '&6Survival sunucusu'
    address: localhost:25569
    restricted: false
player_limit: -1
